


on:
  push:
    branches: [main, stage, dev]
  pull_request:
    branches: [main, stage, dev]
  workflow_dispatch:

name: Check Package ğŸ“¦

jobs:
  check:
    name: Run checks hosted on hta-pharma/ramnog
    uses: hta-pharma/ramnog/.github/workflows/Check-package.yaml@feature/workflows_final
  # audit:
  #   name: Audit Dependencies ğŸ•µï¸â€â™‚ï¸
  #   uses: insightsengineering/r.pkg.template/.github/workflows/audit.yaml@main

  # licenses:
  #   name: License Check ğŸƒ
  #   uses: insightsengineering/r.pkg.template/.github/workflows/licenses.yaml@main

  # check:
  #   name: RMD check ğŸ“¦
  #   uses: ./.github/workflows/R-CMD-check.yaml

  # test:
  #   name: Test ğŸ§ª
  #   uses: ./.github/workflows/Test.yaml

  # gitleaks:
  #   name: gitleaks ğŸ’§
  #   uses: insightsengineering/r.pkg.template/.github/workflows/gitleaks.yaml@main
  #   with:
  #     check-for-pii: true

  # # vbump:
  # #   name: Version Bump ğŸ¤œğŸ¤›
  # #   if: github.event_name == 'push' && github.ref != 'refs/heads/main'
  # #   uses: insightsengineering/r.pkg.template/.github/workflows/version-bump.yaml@main
  # #   with: 
  # #     disable-precommit-autoupdate: true
  # #   secrets:
  # #     REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  
